### ISSUE TITLE
you need to start working

### ISSUE THREAD

**Issue by satuelisa** [EfrenMorales/LabVisionComputacional#1]
the semester is nearly half way through and there is nothing at all in your repository

it sure looks like you plan to flunk the lab

**Comment by EfrenMorales** [comment]
Me disculpo por ello, no tenia idea clara  de como funcionaba python y
github, porque no lo habia utilizado, pero subo este fin de semana lo que
tengo del laboratorio, hice algunas pruebas con unas carpetas de un
tutorial de github, quiza por ello no hay mas que pedazos de una cosa y
otra pero nada claro. Me encargare de subirlo todo lo que tengo hecho en mi
pc para que quede listo para que lo tenga resuelto.

Me disculpo por ello pero son herramientas que no me habian requerido pero
que ahora que las conozco pues les dedicare mas tiempo para armar mi
portafolio de referencias para mi trabajo en un futuro.

Saludos

2015-03-02 8:47 GMT-06:00 satuelisa <notifications@github.com>:

**Comment by satuelisa** [comment]
Sigo esperando que subas algo.

**Comment by satuelisa** [comment]
Aún sin hacer nada y tampoco asistes a las sesiones de laboratorio.

**Comment by satuelisa** [comment]
y sigo esperando; ni asistes las sesiones de laboratorio ni subes nada – espero que te quede claro la certeza de tu reprobación

**Comment by satuelisa** [comment]
Todo esto tiene que quedar listo dentro de un mes.
