### ISSUE TITLE
Deja de copiar cosas de repositorios de otras personas

### ISSUE THREAD

**Issue by satuelisa** [EfrenMorales/LabVisionComputacional#3]
Me queda muy claro qué estás sacando y de donde, no lo dudes. Lo peor es que algunos de los códigos que estás copiando originalmente los escribí yo. 

Si el jueves aún hay código en este repositorio que no es originalmente tuyo sino de otro alumno, no quedarás únicamente reprobado sino también levantaré una queja formal de plagiarismo. 

Tienes tres días y medio para completar los 70 puntos. Ya que no acudiste a la sesión de laboratorio la semana pasada para aclarar dudas, imagino que es por desorganización que no hay actividades recientes en el repositorio.

**Comment by EfrenMorales** [comment]
Lo dare por hecho profesora, lo siento pero no tengo mas opción que aceptar
la critica tal cual, cierto es que la información esta basada en mas de un
alumno, y como es algo que no domino lo acepto tal cual. no entregare nada
y pues que quede en mi nota que estoy reprobado como lo menciona, saludos y
buen dia.

**Comment by satuelisa** [comment]
Tenías todo un semestre para dominar esto. Yo he estado sentado en ese
salón todos los jueves, pero ahí no has estado practicando tú.

Empezar a copiar código la última semana es completamente inaceptable y un
muy mal antecedente laboral. Imagínate luego intentando conseguir empleo en
un lugar donde trabaja una persona de quien copiaste tareas. Obvio que van
a checar tu repositorio hasta antes de entrevistarte. Muchas empresas
también me contactan a mi para preguntar mi opinion sobre postulantes que
son alumnos o egresados del ITS. Te haces mucho daño con estupideces de
este tipo.

**Comment by EfrenMorales** [comment]
No me justificare y acepto las consecuencias, lo que acontece en mi vida a ninguno de los profesores le interesa, y si tengo que tomar decisiones estupidas para sacar la unica materia pendiente para salir ay, pues si tome esa decisión sobre algo que no ocupo. buen dia y le agradezco la marca personal sobre mi persona que menciono.
